apiVersion: 1

datasources:

- name: gdev-prometheus
  uid: gdev-prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  jsonData:
      manageAlerts: true
      alertmanagerUid: gdev-alertmanager